# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies without running any prepare scripts
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Expose port if needed (not required for stdio transport)

# Set the default command to run the MCP server
CMD ["python", "-m", "virustotal_mcp"]
